apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
  namespace: hello-namespace
  labels:
    app: hello-app
spec:
  selector:
    app: hello-app
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
