name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <your-aws-region>

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        run: |
          docker build -t 717813315280.dkr.ecr.eu-central-1.amazonaws.com/hello-ecr-repository:latest .
          docker tag 717813315280.dkr.ecr.eu-central-1.amazonaws.com/hello-ecr-repository:latest 717813315280.dkr.ecr.eu-central-1.amazonaws.com/hello-ecr-repository:${{ github.sha }}

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 717813315280.dkr.ecr.eu-central-1.amazonaws.com/hello-ecr-repository:latest
          docker push 717813315280.dkr.ecr.eu-central-1.amazonaws.com/hello-ecr-repository:${{ github.sha }}
            - name: Version Docker image
            run: |
              version=$(git describe --tags --abbrev=0)
              version="v${version}"
              docker tag 717813315280.dkr.ecr.eu-central-1.amazonaws.com/hello-ecr-repository:${{ github.sha }}717813315280.dkr.ecr.eu-central-1.amazonaws.com/hello-ecr-repository:${version}

            - name: Push versioned Docker image to Amazon ECR
            run: |
              docker push 717813315280.dkr.ecr.eu-central-1.amazonaws.com/hello-ecr-repository:${version}